name: 
author: 
url: https://an-droidx.github.io/Goblog/
baseurl: /Goblog/
resume_site: https://an-droidx.github.io/Goblog/
description: 
github_username: 
github: 
plugins: [jekyll-paginate]
permalink: /:title
paginate: 12
paginate_path: "/page/:num/"
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
highlighter: rouge
markdown: kramdown
comments :
  gitalk :
    clientID : 
    clientSecret : 
    repo : 
    owner : 
    admin : 
